#!/usr/bin/env python3
# Copyright 2026 Duatic AG
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions, and
#    the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions, and
#    the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or
#    promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

"""Check that every CHANGELOG.rst a pull request touches still parses the way bloom reads it.

check_release_pr.py asserts that a release names a version consistently. This asserts the file it
names is still shaped so the notes survive into the .deb. The two failures worth catching are both
silent:

  * a section grouped under sub-headings parses, the version is recognised, and every bullet is
    dropped, so the .deb ships a heading with no notes;
  * a heading that is not `X.Y.Z (YYYY-MM-DD)` is not a version at all, so bloom substitutes
    "Autogenerated, no changelog for this version found" rather than failing.

Checked with catkin_pkg, the parser bloom itself uses, because a regex cannot see either one.

Only files the pull request touches are checked, so a repository converts as it goes rather than
being blocked by a package nobody has reached yet.

Usage:  check_changelog_format.py --base origin/main [--head HEAD]
Exit 0 if every touched changelog is well formed, 1 if not.
"""

import argparse
import os
import re
import subprocess
import sys

from catkin_pkg.changelog import Changelog, populate_changelog_from_rst

# REP-132, and the exact shape catkin_pkg parses: X.Y.Z, one space, a date in parentheses.
SECTION = re.compile(r"^(\d+\.\d+\.\d+) \((.+)\)$", re.M)
DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
# The section for work that is not released yet. catkin writes "Forthcoming"; this name replaces it,
# and prepare_release.py folds it into the version section at release.
PENDING = "Upcoming changes"


def git(*args, allow_fail=False):
    r = subprocess.run(["git", *args], capture_output=True, text=True)
    if r.returncode and not allow_fail:
        raise SystemExit(f'git {" ".join(args)}: {r.stderr.strip()}')
    return r.stdout


def touched_changelogs(base, head):
    names = git("diff", "--name-only", f"{base}...{head}").split()
    return sorted(n for n in names if os.path.basename(n) == "CHANGELOG.rst" and os.path.exists(n))


def underlines(text):
    """Section titles whose underline is shorter than the title. docutils warns and moves on."""
    lines = text.splitlines()
    bad = []
    for i, line in enumerate(lines[:-1]):
        nxt = lines[i + 1]
        if len(nxt) >= 2 and len(set(nxt)) == 1 and nxt[0] in "-~^\"'`#*+=" and line.strip():
            if len(nxt) < len(line):
                bad.append(line)
    return bad


def check(path):
    problems = []
    text = open(path, encoding="utf-8").read()

    if not os.path.exists(os.path.join(os.path.dirname(path), "package.xml")):
        problems.append(
            "no package.xml beside it: bloom looks for the changelog next to the manifest"
        )
        return problems

    changelog = Changelog()
    try:
        populate_changelog_from_rst(changelog, text)
    except Exception as e:  # noqa: BLE001 - any parse failure is the finding
        problems.append(f"does not parse as reStructuredText: {e}")
        return problems

    versions = {v: content for v, _, content in changelog.foreach_version()}

    for title in re.findall(r"^(?!\s)(\S.*)$", text, re.M):
        if SECTION.match(title):
            date = SECTION.match(title).group(2)
            if not DATE.match(date):
                problems.append(f'"{title}": the date must be YYYY-MM-DD')

    for version, content in versions.items():
        if not content:
            problems.append(
                f'section "{version}" parses but holds nothing. Sub-headings inside a version drop '
                f"every bullet under them; keep one flat list"
            )

    if "Forthcoming" in text:
        problems.append(f'uses "Forthcoming"; this repository calls that section "{PENDING}"')

    if not versions and PENDING not in text:
        problems.append(
            f'no version section and no "{PENDING}" section: nothing here reaches the .deb. '
            f"A Markdown changelog parses to exactly this"
        )

    for title in underlines(text):
        problems.append(f'"{title}": the underline is shorter than the title')

    return problems


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--base", required=True, help="the ref to diff against, e.g. origin/main")
    parser.add_argument("--head", default="HEAD")
    args = parser.parse_args()

    paths = touched_changelogs(args.base, args.head)
    if not paths:
        print("no CHANGELOG.rst touched")
        return 0

    bad = 0
    for path in paths:
        problems = check(path)
        if problems:
            bad += 1
            for p in problems:
                print(f"::error file={path}::{p}")
        else:
            print(f"  ok  {path}")

    if bad:
        print(f"\n{bad} of {len(paths)} touched changelogs are malformed")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
